<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dotm</groupId>
        <artifactId>DotmCloud</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>dotm-gateway</artifactId>

    <dependencies>
        <!-- nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId><!-- nacos 服务注册发现 -->
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId><!-- nacos 服务配置中心 -->
        </dependency>
        <!-- nacos -->

        <!--security-->
        <dependency>
            <groupId>com.framework</groupId>
            <artifactId>dotm-framework-security-starter-gateway</artifactId>
            <exclusions>
                <!--不引入core因为不兼容响应式-->
                <exclusion>
                    <groupId>com.framework</groupId>
                    <artifactId>dotm-framework-core</artifactId>
                </exclusion>
                <!--不引入security包 因为api引用了UserDetails但是这个模块没有实现 直接排除完整包-->
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-security</artifactId><!--完整-->
                </exclusion>
            </exclusions>
        </dependency>

        <!--redis 携带common模块-->
        <dependency>
            <groupId>com.framework</groupId>
            <artifactId>dotm-framework-redis</artifactId>
        </dependency>

        <!-- Gateway -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway-server-webflux</artifactId>
        </dependency>

        <!--负载均衡-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

        <!-- JSON 解析器和生成器 -->
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>

        <!--路由检测-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

</project>