server:
  port: ${AUTH_MONITOR_PORT:9999}
spring:
  profiles:
    active: ${AUTH_MONITOR_PROFILE}
  application:
    name: auth-monitor-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_HOST_PORT}
      config:
        server-addr: ${NACOS_SERVER_HOST_PORT}
        group: ${NACOS_GROUP}
  config:
    import:
      - optional:nacos:application-common.yaml?refreshEnabled=true&group=${NACOS_GROUP}
      - optional:nacos:application-dev.yaml?refreshEnabled=true&group=${NACOS_GROUP}