<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dotm</groupId>
        <artifactId>dotm-monitor</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>dotm-monitor-system</artifactId>

    <dependencies>
        <!--core-->
        <dependency>
            <groupId>com.framework</groupId>
            <artifactId>dotm-framework-core</artifactId>
        </dependency>

        <!-- OSHI 核心库 -->
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
        </dependency>

        <!-- nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId><!-- nacos 服务注册发现 -->
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId><!-- nacos 服务配置中心 -->
        </dependency>
        <!-- nacos -->
    </dependencies>

</project>